//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trident.Staging {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.mother.com", ConfigurationName="Staging.ITMSeChallanImpl")]
    public interface ITMSeChallanImpl {
        
        // CODEGEN: Generating message contract since element name getUnitsReturn from namespace http://service.mother.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Trident.Staging.getUnitsResponse getUnits(Trident.Staging.getUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Trident.Staging.getUnitsResponse> getUnitsAsync(Trident.Staging.getUnitsRequest request);
        
        // CODEGEN: Generating message contract since element name cameraID from namespace http://service.mother.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Trident.Staging.generateChallanResponse generateChallan(Trident.Staging.generateChallanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Trident.Staging.generateChallanResponse> generateChallanAsync(Trident.Staging.generateChallanRequest request);
        
        // CODEGEN: Generating message contract since element name pidCd from namespace http://service.mother.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Trident.Staging.laserGunTabLoginResponse laserGunTabLogin(Trident.Staging.laserGunTabLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Trident.Staging.laserGunTabLoginResponse> laserGunTabLoginAsync(Trident.Staging.laserGunTabLoginRequest request);
        
        // CODEGEN: Generating message contract since element name cameraID from namespace http://service.mother.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Trident.Staging.generateCameraPIDResponse generateCameraPID(Trident.Staging.generateCameraPIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Trident.Staging.generateCameraPIDResponse> generateCameraPIDAsync(Trident.Staging.generateCameraPIDRequest request);
        
        // CODEGEN: Generating message contract since element name unitCode from namespace http://service.mother.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Trident.Staging.getPoliceStationsResponse getPoliceStations(Trident.Staging.getPoliceStationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Trident.Staging.getPoliceStationsResponse> getPoliceStationsAsync(Trident.Staging.getPoliceStationsRequest request);
        
        // CODEGEN: Generating message contract since element name psCode from namespace http://service.mother.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Trident.Staging.getpointsResponse getpoints(Trident.Staging.getpointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Trident.Staging.getpointsResponse> getpointsAsync(Trident.Staging.getpointsRequest request);
        
        // CODEGEN: Generating message contract since element name psCode from namespace http://service.mother.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Trident.Staging.getOfficersResponse getOfficers(Trident.Staging.getOfficersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Trident.Staging.getOfficersResponse> getOfficersAsync(Trident.Staging.getOfficersRequest request);
        
        // CODEGEN: Generating message contract since element name regnNo from namespace http://service.mother.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Trident.Staging.getVehicleDetailsResponse getVehicleDetails(Trident.Staging.getVehicleDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Trident.Staging.getVehicleDetailsResponse> getVehicleDetailsAsync(Trident.Staging.getVehicleDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUnits", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getUnitsRequestBody Body;
        
        public getUnitsRequest() {
        }
        
        public getUnitsRequest(Trident.Staging.getUnitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUnitsRequestBody {
        
        public getUnitsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUnitsResponse", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getUnitsResponseBody Body;
        
        public getUnitsResponse() {
        }
        
        public getUnitsResponse(Trident.Staging.getUnitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class getUnitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUnitsReturn;
        
        public getUnitsResponseBody() {
        }
        
        public getUnitsResponseBody(string getUnitsReturn) {
            this.getUnitsReturn = getUnitsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateChallanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateChallan", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.generateChallanRequestBody Body;
        
        public generateChallanRequest() {
        }
        
        public generateChallanRequest(Trident.Staging.generateChallanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class generateChallanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cameraID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string transID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cameSecKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cameraIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string systemID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string timeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string IsItTempRegn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string registrationNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string wheelerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string vioCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string speedLimit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string vehicleSpeed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string xtraPassengers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string frontalImgURLs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string contextImgURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string lpImgURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string anprVideoURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string contextVideoURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string masterBase64Img;
        
        public generateChallanRequestBody() {
        }
        
        public generateChallanRequestBody(
                    string cameraID, 
                    string transID, 
                    string cameSecKey, 
                    string cameraIP, 
                    string systemID, 
                    string userId, 
                    string userName, 
                    string timeStamp, 
                    string IsItTempRegn, 
                    string registrationNo, 
                    string wheelerCode, 
                    string vioCode, 
                    string speedLimit, 
                    string vehicleSpeed, 
                    string xtraPassengers, 
                    string frontalImgURLs, 
                    string contextImgURL, 
                    string lpImgURL, 
                    string anprVideoURL, 
                    string contextVideoURL, 
                    string masterBase64Img) {
            this.cameraID = cameraID;
            this.transID = transID;
            this.cameSecKey = cameSecKey;
            this.cameraIP = cameraIP;
            this.systemID = systemID;
            this.userId = userId;
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.IsItTempRegn = IsItTempRegn;
            this.registrationNo = registrationNo;
            this.wheelerCode = wheelerCode;
            this.vioCode = vioCode;
            this.speedLimit = speedLimit;
            this.vehicleSpeed = vehicleSpeed;
            this.xtraPassengers = xtraPassengers;
            this.frontalImgURLs = frontalImgURLs;
            this.contextImgURL = contextImgURL;
            this.lpImgURL = lpImgURL;
            this.anprVideoURL = anprVideoURL;
            this.contextVideoURL = contextVideoURL;
            this.masterBase64Img = masterBase64Img;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateChallanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateChallanResponse", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.generateChallanResponseBody Body;
        
        public generateChallanResponse() {
        }
        
        public generateChallanResponse(Trident.Staging.generateChallanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class generateChallanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string generateChallanReturn;
        
        public generateChallanResponseBody() {
        }
        
        public generateChallanResponseBody(string generateChallanReturn) {
            this.generateChallanReturn = generateChallanReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laserGunTabLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="laserGunTabLogin", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.laserGunTabLoginRequestBody Body;
        
        public laserGunTabLoginRequest() {
        }
        
        public laserGunTabLoginRequest(Trident.Staging.laserGunTabLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class laserGunTabLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pidCd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string imeiNo;
        
        public laserGunTabLoginRequestBody() {
        }
        
        public laserGunTabLoginRequestBody(string pidCd, string password, string imeiNo) {
            this.pidCd = pidCd;
            this.password = password;
            this.imeiNo = imeiNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laserGunTabLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="laserGunTabLoginResponse", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.laserGunTabLoginResponseBody Body;
        
        public laserGunTabLoginResponse() {
        }
        
        public laserGunTabLoginResponse(Trident.Staging.laserGunTabLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class laserGunTabLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string laserGunTabLoginReturn;
        
        public laserGunTabLoginResponseBody() {
        }
        
        public laserGunTabLoginResponseBody(string laserGunTabLoginReturn) {
            this.laserGunTabLoginReturn = laserGunTabLoginReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateCameraPIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateCameraPID", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.generateCameraPIDRequestBody Body;
        
        public generateCameraPIDRequest() {
        }
        
        public generateCameraPIDRequest(Trident.Staging.generateCameraPIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class generateCameraPIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cameraID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cameraIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string unitCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string psCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pointCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string gpsLatti;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string gpsLong;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SystemID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string CameraSecuritySKey;
        
        public generateCameraPIDRequestBody() {
        }
        
        public generateCameraPIDRequestBody(string cameraID, string cameraIP, string unitCode, string psCode, string pointCode, string location, string gpsLatti, string gpsLong, string SystemID, string userId, string CameraSecuritySKey) {
            this.cameraID = cameraID;
            this.cameraIP = cameraIP;
            this.unitCode = unitCode;
            this.psCode = psCode;
            this.pointCode = pointCode;
            this.location = location;
            this.gpsLatti = gpsLatti;
            this.gpsLong = gpsLong;
            this.SystemID = SystemID;
            this.userId = userId;
            this.CameraSecuritySKey = CameraSecuritySKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateCameraPIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateCameraPIDResponse", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.generateCameraPIDResponseBody Body;
        
        public generateCameraPIDResponse() {
        }
        
        public generateCameraPIDResponse(Trident.Staging.generateCameraPIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class generateCameraPIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string generateCameraPIDReturn;
        
        public generateCameraPIDResponseBody() {
        }
        
        public generateCameraPIDResponseBody(string generateCameraPIDReturn) {
            this.generateCameraPIDReturn = generateCameraPIDReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPoliceStationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPoliceStations", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getPoliceStationsRequestBody Body;
        
        public getPoliceStationsRequest() {
        }
        
        public getPoliceStationsRequest(Trident.Staging.getPoliceStationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class getPoliceStationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string unitCode;
        
        public getPoliceStationsRequestBody() {
        }
        
        public getPoliceStationsRequestBody(string unitCode) {
            this.unitCode = unitCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPoliceStationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPoliceStationsResponse", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getPoliceStationsResponseBody Body;
        
        public getPoliceStationsResponse() {
        }
        
        public getPoliceStationsResponse(Trident.Staging.getPoliceStationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class getPoliceStationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPoliceStationsReturn;
        
        public getPoliceStationsResponseBody() {
        }
        
        public getPoliceStationsResponseBody(string getPoliceStationsReturn) {
            this.getPoliceStationsReturn = getPoliceStationsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getpointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getpoints", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getpointsRequestBody Body;
        
        public getpointsRequest() {
        }
        
        public getpointsRequest(Trident.Staging.getpointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class getpointsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psCode;
        
        public getpointsRequestBody() {
        }
        
        public getpointsRequestBody(string psCode) {
            this.psCode = psCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getpointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getpointsResponse", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getpointsResponseBody Body;
        
        public getpointsResponse() {
        }
        
        public getpointsResponse(Trident.Staging.getpointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class getpointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getpointsReturn;
        
        public getpointsResponseBody() {
        }
        
        public getpointsResponseBody(string getpointsReturn) {
            this.getpointsReturn = getpointsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOfficersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOfficers", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getOfficersRequestBody Body;
        
        public getOfficersRequest() {
        }
        
        public getOfficersRequest(Trident.Staging.getOfficersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class getOfficersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psCode;
        
        public getOfficersRequestBody() {
        }
        
        public getOfficersRequestBody(string psCode) {
            this.psCode = psCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOfficersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOfficersResponse", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getOfficersResponseBody Body;
        
        public getOfficersResponse() {
        }
        
        public getOfficersResponse(Trident.Staging.getOfficersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class getOfficersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getOfficersReturn;
        
        public getOfficersResponseBody() {
        }
        
        public getOfficersResponseBody(string getOfficersReturn) {
            this.getOfficersReturn = getOfficersReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVehicleDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVehicleDetails", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getVehicleDetailsRequestBody Body;
        
        public getVehicleDetailsRequest() {
        }
        
        public getVehicleDetailsRequest(Trident.Staging.getVehicleDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class getVehicleDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string regnNo;
        
        public getVehicleDetailsRequestBody() {
        }
        
        public getVehicleDetailsRequestBody(string regnNo) {
            this.regnNo = regnNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVehicleDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVehicleDetailsResponse", Namespace="http://service.mother.com", Order=0)]
        public Trident.Staging.getVehicleDetailsResponseBody Body;
        
        public getVehicleDetailsResponse() {
        }
        
        public getVehicleDetailsResponse(Trident.Staging.getVehicleDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mother.com")]
    public partial class getVehicleDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getVehicleDetailsReturn;
        
        public getVehicleDetailsResponseBody() {
        }
        
        public getVehicleDetailsResponseBody(string getVehicleDetailsReturn) {
            this.getVehicleDetailsReturn = getVehicleDetailsReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITMSeChallanImplChannel : Trident.Staging.ITMSeChallanImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TMSeChallanImplClient : System.ServiceModel.ClientBase<Trident.Staging.ITMSeChallanImpl>, Trident.Staging.ITMSeChallanImpl {
        
        public TMSeChallanImplClient() {
        }
        
        public TMSeChallanImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TMSeChallanImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSeChallanImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSeChallanImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trident.Staging.getUnitsResponse Trident.Staging.ITMSeChallanImpl.getUnits(Trident.Staging.getUnitsRequest request) {
            return base.Channel.getUnits(request);
        }
        
        public string getUnits() {
            Trident.Staging.getUnitsRequest inValue = new Trident.Staging.getUnitsRequest();
            inValue.Body = new Trident.Staging.getUnitsRequestBody();
            Trident.Staging.getUnitsResponse retVal = ((Trident.Staging.ITMSeChallanImpl)(this)).getUnits(inValue);
            return retVal.Body.getUnitsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trident.Staging.getUnitsResponse> Trident.Staging.ITMSeChallanImpl.getUnitsAsync(Trident.Staging.getUnitsRequest request) {
            return base.Channel.getUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trident.Staging.getUnitsResponse> getUnitsAsync() {
            Trident.Staging.getUnitsRequest inValue = new Trident.Staging.getUnitsRequest();
            inValue.Body = new Trident.Staging.getUnitsRequestBody();
            return ((Trident.Staging.ITMSeChallanImpl)(this)).getUnitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trident.Staging.generateChallanResponse Trident.Staging.ITMSeChallanImpl.generateChallan(Trident.Staging.generateChallanRequest request) {
            return base.Channel.generateChallan(request);
        }
        
        public string generateChallan(
                    string cameraID, 
                    string transID, 
                    string cameSecKey, 
                    string cameraIP, 
                    string systemID, 
                    string userId, 
                    string userName, 
                    string timeStamp, 
                    string IsItTempRegn, 
                    string registrationNo, 
                    string wheelerCode, 
                    string vioCode, 
                    string speedLimit, 
                    string vehicleSpeed, 
                    string xtraPassengers, 
                    string frontalImgURLs, 
                    string contextImgURL, 
                    string lpImgURL, 
                    string anprVideoURL, 
                    string contextVideoURL, 
                    string masterBase64Img) {
            Trident.Staging.generateChallanRequest inValue = new Trident.Staging.generateChallanRequest();
            inValue.Body = new Trident.Staging.generateChallanRequestBody();
            inValue.Body.cameraID = cameraID;
            inValue.Body.transID = transID;
            inValue.Body.cameSecKey = cameSecKey;
            inValue.Body.cameraIP = cameraIP;
            inValue.Body.systemID = systemID;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.IsItTempRegn = IsItTempRegn;
            inValue.Body.registrationNo = registrationNo;
            inValue.Body.wheelerCode = wheelerCode;
            inValue.Body.vioCode = vioCode;
            inValue.Body.speedLimit = speedLimit;
            inValue.Body.vehicleSpeed = vehicleSpeed;
            inValue.Body.xtraPassengers = xtraPassengers;
            inValue.Body.frontalImgURLs = frontalImgURLs;
            inValue.Body.contextImgURL = contextImgURL;
            inValue.Body.lpImgURL = lpImgURL;
            inValue.Body.anprVideoURL = anprVideoURL;
            inValue.Body.contextVideoURL = contextVideoURL;
            inValue.Body.masterBase64Img = masterBase64Img;
            Trident.Staging.generateChallanResponse retVal = ((Trident.Staging.ITMSeChallanImpl)(this)).generateChallan(inValue);
            return retVal.Body.generateChallanReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trident.Staging.generateChallanResponse> Trident.Staging.ITMSeChallanImpl.generateChallanAsync(Trident.Staging.generateChallanRequest request) {
            return base.Channel.generateChallanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trident.Staging.generateChallanResponse> generateChallanAsync(
                    string cameraID, 
                    string transID, 
                    string cameSecKey, 
                    string cameraIP, 
                    string systemID, 
                    string userId, 
                    string userName, 
                    string timeStamp, 
                    string IsItTempRegn, 
                    string registrationNo, 
                    string wheelerCode, 
                    string vioCode, 
                    string speedLimit, 
                    string vehicleSpeed, 
                    string xtraPassengers, 
                    string frontalImgURLs, 
                    string contextImgURL, 
                    string lpImgURL, 
                    string anprVideoURL, 
                    string contextVideoURL, 
                    string masterBase64Img) {
            Trident.Staging.generateChallanRequest inValue = new Trident.Staging.generateChallanRequest();
            inValue.Body = new Trident.Staging.generateChallanRequestBody();
            inValue.Body.cameraID = cameraID;
            inValue.Body.transID = transID;
            inValue.Body.cameSecKey = cameSecKey;
            inValue.Body.cameraIP = cameraIP;
            inValue.Body.systemID = systemID;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.IsItTempRegn = IsItTempRegn;
            inValue.Body.registrationNo = registrationNo;
            inValue.Body.wheelerCode = wheelerCode;
            inValue.Body.vioCode = vioCode;
            inValue.Body.speedLimit = speedLimit;
            inValue.Body.vehicleSpeed = vehicleSpeed;
            inValue.Body.xtraPassengers = xtraPassengers;
            inValue.Body.frontalImgURLs = frontalImgURLs;
            inValue.Body.contextImgURL = contextImgURL;
            inValue.Body.lpImgURL = lpImgURL;
            inValue.Body.anprVideoURL = anprVideoURL;
            inValue.Body.contextVideoURL = contextVideoURL;
            inValue.Body.masterBase64Img = masterBase64Img;
            return ((Trident.Staging.ITMSeChallanImpl)(this)).generateChallanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trident.Staging.laserGunTabLoginResponse Trident.Staging.ITMSeChallanImpl.laserGunTabLogin(Trident.Staging.laserGunTabLoginRequest request) {
            return base.Channel.laserGunTabLogin(request);
        }
        
        public string laserGunTabLogin(string pidCd, string password, string imeiNo) {
            Trident.Staging.laserGunTabLoginRequest inValue = new Trident.Staging.laserGunTabLoginRequest();
            inValue.Body = new Trident.Staging.laserGunTabLoginRequestBody();
            inValue.Body.pidCd = pidCd;
            inValue.Body.password = password;
            inValue.Body.imeiNo = imeiNo;
            Trident.Staging.laserGunTabLoginResponse retVal = ((Trident.Staging.ITMSeChallanImpl)(this)).laserGunTabLogin(inValue);
            return retVal.Body.laserGunTabLoginReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trident.Staging.laserGunTabLoginResponse> Trident.Staging.ITMSeChallanImpl.laserGunTabLoginAsync(Trident.Staging.laserGunTabLoginRequest request) {
            return base.Channel.laserGunTabLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trident.Staging.laserGunTabLoginResponse> laserGunTabLoginAsync(string pidCd, string password, string imeiNo) {
            Trident.Staging.laserGunTabLoginRequest inValue = new Trident.Staging.laserGunTabLoginRequest();
            inValue.Body = new Trident.Staging.laserGunTabLoginRequestBody();
            inValue.Body.pidCd = pidCd;
            inValue.Body.password = password;
            inValue.Body.imeiNo = imeiNo;
            return ((Trident.Staging.ITMSeChallanImpl)(this)).laserGunTabLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trident.Staging.generateCameraPIDResponse Trident.Staging.ITMSeChallanImpl.generateCameraPID(Trident.Staging.generateCameraPIDRequest request) {
            return base.Channel.generateCameraPID(request);
        }
        
        public string generateCameraPID(string cameraID, string cameraIP, string unitCode, string psCode, string pointCode, string location, string gpsLatti, string gpsLong, string SystemID, string userId, string CameraSecuritySKey) {
            Trident.Staging.generateCameraPIDRequest inValue = new Trident.Staging.generateCameraPIDRequest();
            inValue.Body = new Trident.Staging.generateCameraPIDRequestBody();
            inValue.Body.cameraID = cameraID;
            inValue.Body.cameraIP = cameraIP;
            inValue.Body.unitCode = unitCode;
            inValue.Body.psCode = psCode;
            inValue.Body.pointCode = pointCode;
            inValue.Body.location = location;
            inValue.Body.gpsLatti = gpsLatti;
            inValue.Body.gpsLong = gpsLong;
            inValue.Body.SystemID = SystemID;
            inValue.Body.userId = userId;
            inValue.Body.CameraSecuritySKey = CameraSecuritySKey;
            Trident.Staging.generateCameraPIDResponse retVal = ((Trident.Staging.ITMSeChallanImpl)(this)).generateCameraPID(inValue);
            return retVal.Body.generateCameraPIDReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trident.Staging.generateCameraPIDResponse> Trident.Staging.ITMSeChallanImpl.generateCameraPIDAsync(Trident.Staging.generateCameraPIDRequest request) {
            return base.Channel.generateCameraPIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trident.Staging.generateCameraPIDResponse> generateCameraPIDAsync(string cameraID, string cameraIP, string unitCode, string psCode, string pointCode, string location, string gpsLatti, string gpsLong, string SystemID, string userId, string CameraSecuritySKey) {
            Trident.Staging.generateCameraPIDRequest inValue = new Trident.Staging.generateCameraPIDRequest();
            inValue.Body = new Trident.Staging.generateCameraPIDRequestBody();
            inValue.Body.cameraID = cameraID;
            inValue.Body.cameraIP = cameraIP;
            inValue.Body.unitCode = unitCode;
            inValue.Body.psCode = psCode;
            inValue.Body.pointCode = pointCode;
            inValue.Body.location = location;
            inValue.Body.gpsLatti = gpsLatti;
            inValue.Body.gpsLong = gpsLong;
            inValue.Body.SystemID = SystemID;
            inValue.Body.userId = userId;
            inValue.Body.CameraSecuritySKey = CameraSecuritySKey;
            return ((Trident.Staging.ITMSeChallanImpl)(this)).generateCameraPIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trident.Staging.getPoliceStationsResponse Trident.Staging.ITMSeChallanImpl.getPoliceStations(Trident.Staging.getPoliceStationsRequest request) {
            return base.Channel.getPoliceStations(request);
        }
        
        public string getPoliceStations(string unitCode) {
            Trident.Staging.getPoliceStationsRequest inValue = new Trident.Staging.getPoliceStationsRequest();
            inValue.Body = new Trident.Staging.getPoliceStationsRequestBody();
            inValue.Body.unitCode = unitCode;
            Trident.Staging.getPoliceStationsResponse retVal = ((Trident.Staging.ITMSeChallanImpl)(this)).getPoliceStations(inValue);
            return retVal.Body.getPoliceStationsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trident.Staging.getPoliceStationsResponse> Trident.Staging.ITMSeChallanImpl.getPoliceStationsAsync(Trident.Staging.getPoliceStationsRequest request) {
            return base.Channel.getPoliceStationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trident.Staging.getPoliceStationsResponse> getPoliceStationsAsync(string unitCode) {
            Trident.Staging.getPoliceStationsRequest inValue = new Trident.Staging.getPoliceStationsRequest();
            inValue.Body = new Trident.Staging.getPoliceStationsRequestBody();
            inValue.Body.unitCode = unitCode;
            return ((Trident.Staging.ITMSeChallanImpl)(this)).getPoliceStationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trident.Staging.getpointsResponse Trident.Staging.ITMSeChallanImpl.getpoints(Trident.Staging.getpointsRequest request) {
            return base.Channel.getpoints(request);
        }
        
        public string getpoints(string psCode) {
            Trident.Staging.getpointsRequest inValue = new Trident.Staging.getpointsRequest();
            inValue.Body = new Trident.Staging.getpointsRequestBody();
            inValue.Body.psCode = psCode;
            Trident.Staging.getpointsResponse retVal = ((Trident.Staging.ITMSeChallanImpl)(this)).getpoints(inValue);
            return retVal.Body.getpointsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trident.Staging.getpointsResponse> Trident.Staging.ITMSeChallanImpl.getpointsAsync(Trident.Staging.getpointsRequest request) {
            return base.Channel.getpointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trident.Staging.getpointsResponse> getpointsAsync(string psCode) {
            Trident.Staging.getpointsRequest inValue = new Trident.Staging.getpointsRequest();
            inValue.Body = new Trident.Staging.getpointsRequestBody();
            inValue.Body.psCode = psCode;
            return ((Trident.Staging.ITMSeChallanImpl)(this)).getpointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trident.Staging.getOfficersResponse Trident.Staging.ITMSeChallanImpl.getOfficers(Trident.Staging.getOfficersRequest request) {
            return base.Channel.getOfficers(request);
        }
        
        public string getOfficers(string psCode) {
            Trident.Staging.getOfficersRequest inValue = new Trident.Staging.getOfficersRequest();
            inValue.Body = new Trident.Staging.getOfficersRequestBody();
            inValue.Body.psCode = psCode;
            Trident.Staging.getOfficersResponse retVal = ((Trident.Staging.ITMSeChallanImpl)(this)).getOfficers(inValue);
            return retVal.Body.getOfficersReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trident.Staging.getOfficersResponse> Trident.Staging.ITMSeChallanImpl.getOfficersAsync(Trident.Staging.getOfficersRequest request) {
            return base.Channel.getOfficersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trident.Staging.getOfficersResponse> getOfficersAsync(string psCode) {
            Trident.Staging.getOfficersRequest inValue = new Trident.Staging.getOfficersRequest();
            inValue.Body = new Trident.Staging.getOfficersRequestBody();
            inValue.Body.psCode = psCode;
            return ((Trident.Staging.ITMSeChallanImpl)(this)).getOfficersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trident.Staging.getVehicleDetailsResponse Trident.Staging.ITMSeChallanImpl.getVehicleDetails(Trident.Staging.getVehicleDetailsRequest request) {
            return base.Channel.getVehicleDetails(request);
        }
        
        public string getVehicleDetails(string regnNo) {
            Trident.Staging.getVehicleDetailsRequest inValue = new Trident.Staging.getVehicleDetailsRequest();
            inValue.Body = new Trident.Staging.getVehicleDetailsRequestBody();
            inValue.Body.regnNo = regnNo;
            Trident.Staging.getVehicleDetailsResponse retVal = ((Trident.Staging.ITMSeChallanImpl)(this)).getVehicleDetails(inValue);
            return retVal.Body.getVehicleDetailsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trident.Staging.getVehicleDetailsResponse> Trident.Staging.ITMSeChallanImpl.getVehicleDetailsAsync(Trident.Staging.getVehicleDetailsRequest request) {
            return base.Channel.getVehicleDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trident.Staging.getVehicleDetailsResponse> getVehicleDetailsAsync(string regnNo) {
            Trident.Staging.getVehicleDetailsRequest inValue = new Trident.Staging.getVehicleDetailsRequest();
            inValue.Body = new Trident.Staging.getVehicleDetailsRequestBody();
            inValue.Body.regnNo = regnNo;
            return ((Trident.Staging.ITMSeChallanImpl)(this)).getVehicleDetailsAsync(inValue);
        }
    }
}
